version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: smart-contract-analyzer-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - HUGGINGFACE_API_TOKEN=${HUGGINGFACE_API_TOKEN:-}
    volumes:
      - ./backend:/app
    networks:
      - analyzer-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: smart-contract-analyzer-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - analyzer-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  analyzer-network:
    driver: bridge

volumes:
  analysis-cache:
    driver: local
